name : Publish

on: [ workflow_dispatch ]      

permissions:
  contents: write

env:                                              
  MINECRAFT_VERSION: 1.19.2                        
  JAVA_VERSION: 17      
  VERSION: 0.2+1.19.2  
  RELEASE_NAME: Create-Metal-0.2-mc1.19.2
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check_env
        run: env

      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: setup_Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: run_gradle_wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew clean build

      - name: push_artifact
        uses: actions/upload-artifact@v2
        with:
          name: create-metal-artifacts
          path: build/libs/*[0-9].jar
          
      - name: publish
        uses: Kir-Antipov/mc-publish@v3.2                                   
        with:
          
          modrinth-id: CXmmsH8g                                            
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"                             
          version: "${{env.VERSION}}"
          version-type: release                                    

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
